Repository wonny1012/LikeLion_Team12, pull requests merged in 2023-11, with the labels that each got.

#1 프로젝트 생성
  API_Practice/API_Practice.xcodeproj/project.pbxproj
  API_Practice/API_Practice.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  API_Practice/API_Practice.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  API_Practice/API_Practice/API_PracticeApp.swift
  API_Practice/API_Practice/Assets.xcassets/AccentColor.colorset/Contents.json
  API_Practice/API_Practice/Assets.xcassets/AppIcon.appiconset/Contents.json
  API_Practice/API_Practice/Assets.xcassets/Contents.json
  API_Practice/API_Practice/ContentView.swift
  API_Practice/API_Practice/JiwonView.swift
  API_Practice/API_Practice/Preview Content/Preview Assets.xcassets/Contents.json
  환경세팅.txt
Labels: ✨Feature, 🐼 지원

#7 API 호출 기능 구현
  .DS_Store
  API_Practice/.DS_Store
  API_Practice/API_Practice.xcodeproj/project.pbxproj
  API_Practice/API_Practice.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  API_Practice/API_Practice/ContentView.swift
  API_Practice/API_Practice/Hyunjin/HyunjinView.swift
  API_Practice/API_Practice/Hyunjin/NFTModels.swift
Labels: ✨Feature, 현진

#6 Develop More: get additional detail data(genera) from the API
  API_Practice/API_Practice/Eunsu/Managers/PokemonManager.swift
  API_Practice/API_Practice/Eunsu/PokemonModels/PokemonModel.swift
  API_Practice/API_Practice/Eunsu/PokemonViewModels/PokemonViewModel.swift
  API_Practice/API_Practice/Eunsu/PokemonViews/EunsuView.swift
  API_Practice/API_Practice/Eunsu/PokemonViews/PokemonDetailView.swift
  README.md
Labels: ✨Feature, ♻️Refactoring, 🌱은수, 🐞Fix
